#!/usr/bin/env python
"""
manage.py — Django's command-line utility
=========================================

This is the entry point for all Django administrative commands.

When you run, for example:

    python manage.py runserver
    python manage.py migrate
    python manage.py createsuperuser

...this file is what gets executed. It sets up the Django environment
and passes the command-line arguments to django.core.management's
execute_from_command_line() function, which handles the rest.

Key concepts:
  - The shebang line (#!/usr/bin/env python) allows the file to be
    executed directly as a script on Unix systems (./manage.py).
  - DJANGO_SETTINGS_MODULE tells Django which settings file to use.
    Without it, Django would not know your database config, installed
    apps, etc.
  - The try/except block provides a helpful error message if Django
    is not installed or not on the Python path.

You should never need to modify this file. It is generated by
`django-admin startproject` and is the same across almost every
Django project.
"""

import os
import sys


def main():
    """
    Set the default Django settings module and run the command.

    This function exists so we can call it conditionally (only when
    this file is executed directly, not when it is imported as a
    module). This is the standard Django pattern.
    """
    # --- Tell Django which settings to use ------------------------------
    # os.environ is a dictionary of environment variables.
    # setdefault(key, value) sets the value ONLY if the key does not
    # already exist. This means you can override it by setting the
    # environment variable before running the command:
    #
    #   export DJANGO_SETTINGS_MODULE=car_crm.production_settings
    #   python manage.py runserver
    #
    # os.environ behaves like a dict, but setdefault is a standard
    # Python dict method (not os-specific).
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'car_crm.settings')

    # --- Try to import Django's management module -----------------------
    try:
        # The import is inside the function (not at the top of the file)
        # so that importing manage.py itself (e.g. from another script)
        # does not trigger Django setup.
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        # If Django is not installed or not on PYTHONPATH, we raise
        # a descriptive error. The "from exc" syntax (PEP 3134) chains
        # exceptions so the original traceback is preserved.
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    # --- Execute the command -------------------------------------------
    # sys.argv is the list of command-line arguments passed to the
    # script (e.g. ['manage.py', 'runserver', '0.0.0.0:8000']).
    # execute_from_command_line parses these and dispatches to the
    # appropriate management command.
    execute_from_command_line(sys.argv)


# --- Standard Python entry-point guard ----------------------------------
# This conditional ensures that main() is only called when the file
# is executed directly (e.g. `python manage.py runserver`), NOT when
# it is imported as a module in another file.
#
# __name__ is a special Python variable:
#   - "__main__" when the script is run directly.
#   - The module's name (e.g. "manage") when imported.
if __name__ == '__main__':
    main()
