# Generated by Django 6.0.7 on 2026-07-08 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, help_text='Optional URL when banner is clicked', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('featured', 'Featured'), ('sale', 'Sale'), ('new', 'New Arrival'), ('hot', 'Hot Deal')], default='featured', max_length=10)),
                ('discount_percent', models.SmallIntegerField(blank=True, help_text='Discount percentage (e.g. 15 for 15% off)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='vehicles.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
